import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-5xl mx-auto p-4">
          <Header />
          {children}
          <footer className="py-8 border-t">
            <div className="container mx-auto flex justify-between items-center">
              <p className="text-sm">
                &copy; 2023 Feastify. All rights reserved.
              </p>
              <div className="flex space-x-4">
                <a href="#" className="text-gray-500">
                  Privacy Policy
                </a>
                <a href="#" className="text-gray-500">
                  Terms of Service
                </a>
              </div>
            </div>
          </footer>
        </main>
      </body>
    </html>
  );
}
